### PR TITLE
Update README.md and adding some extra steps

### PR DESCRIPTION
**Pull request by AlexonOliveiraRH**
Included a hyperlink for the index file related to the instructions of the lab. This way is easier for the user to know where to go to get started.

Adding a step to instruct the needing of changing the UUID parameter in all preconfigured yaml files previous to start applying them.

Highlighting the importance of keeping the double quotes to be able to download the KVM guest image from Customer Portal.

### CODE REVIEW

**Comment by spotzz** [comment]
Alexon, I  actually purposely left the UUID script out of the instructions to force people to have to actually look at the Yamls:)

**Comment by AlexonOliveiraRH** [comment]
> Alexon, I actually purposely left the UUID script out of the instructions to force people to have to actually look at the Yamls:)

Oh, got it. So we can left this one out and keep the other commits, please?

**Review by AlexonOliveiraRH — COMMENTED** [review]
Accepting proposed changes

**Comment by AlexonOliveiraRH** [comment]
@spotzz done. PR updated as per your instruction. Could you review it again, please?

**Review by spotzz — APPROVED** [review]
looks good, thanks

**Pull request merged**
